# https://numtide.github.io/devshell
[[commands]]
package = "devshell.cli"
help = "Per project developer environments"

[[commands]]
package = "elixir"
help = "Elixir Language"

[[commands]]
package = "elixir_ls"
help = "Elixir Language Server"
